# Configuration file

title: Anjos sem Asa
# email: lorenzo@lorenzocesconetto.com
description: > # this means to ignore newlines until "baseurl:"
  Somos um programa que visa levar crianças de escolar públicas até as melhores universidades do Brasil e do mundo.
permalink: ':title/'

baseurl: "/anjos-sem-asa" # the subpath of your site, e.g. /blog
url: "http://lorenzocesconetto.com" # the base hostname & protocol for your site, e.g. http://example.com

# Set Timezone in Sao Paulo
timezone: America/Sao_Paulo

# Author settings
author: Anjos sem Asa # add your name

# Contact links
# email: lorenzo@lorenzocesconetto.com # Add your Email address

# phone: # Add your Phone number
# website: lorenzocesconetto.com # Add your website, do not add http://
# linkedin: /lorenzo-cesconetto/ # Add your Linkedin handle
# facebook: lorenzo.cesconeto # Add your Facebook handle
# instagram: lorenzocesconeto # Add your Instagram handle

# Newsletter
# mailchimp: lorenzocesconetto.us17.list-manage.com/subscribe/post?u=58a81bd5376d7fcccb57e2ce6&amp;id=4bb34e0f21 # Add your MailChimp form identifier.

# Disqus
# discus_identifier: lorenzocesconetto-com # Add your discus identifier

# Tracker
# analytics: UA-111507718-1 # Google Analytics

# Build settings
# markdown: kramdown

# plugins:
#   - jekyll-feed
#   - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]



